apiVersion: apps/v1
kind: Deployment
metadata:
    name: commandservice-depl
    namespace: practice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: commandservice-prc
    template:
        metadata:
            labels:
                app: commandservice-prc
        spec:
            containers:
                - name: commandservice-prc
                  image: mukundhak/commandservicepractice
---
apiVersion: v1
kind: Service
metadata:
    name: commandservice-clusterip-srv
    namespace: practice
spec:
    type: ClusterIP
    selector:
        app: commandservice-prc
    ports:
        - name: commandservice-prc
          protocol: TCP
          port: 80
          targetPort: 80