apiVersion: v1
kind: Service
metadata: 
    name: platformservice-prc-np-srv
spec:
    type: NodePort
    selector:
        app: platforservice-prc
    ports:
        - name: platforservice-prc
          protocol: TCP
          port: 80
          targetPort: 80